---
title: "Assignment 5"
Date: OCtober 17th 2019
Author: Linda Dumalo 
output: html_document
---


```{r setup, include=FALSE}
library(gapminder)
library(dplyr)
library(forcats)
library(ggplot2)
```

## **Exercise 2:** Factor Management 

```{r results='hide'}
gapminder
```

The variables that are factors in the gapminder dataset are **country** and **continent**. Observations assoicated with "Ocenia" will be removed along with unused factor levels. 

To compare how dropping factors and using arange affects data, the tibble with the dropped factors will be dubbded as "gap."


```{r v0}
gap= gapminder %>% 
  filter(continent %in% c("Africa", "Asia", "Europe", "Americas")) %>% 
  droplevels()
levels(gap$continent)
  # should have some code here to display that it worked... 
```


Going to look at total GDP for the year 1997  

```{r v0: not using factors + ugly} 
gap %>%  
  filter(year == 1997) %>% 
  mutate(gdpTotal = gdpPercap*pop) %>%  
  group_by(continent) %>%
  summarize(av_gdpTotal = mean(gdpTotal)) %>% 
  ggplot(aes(continent, av_gdpTotal)) + 
  geom_histogram(stat="identity") 

```

```{r}
gap %>%  
  filter(year == 1997) %>% 
  mutate(gdpTotal = gdpPercap*pop) %>%  
  ggplot(aes(fct_reorder(country, gdpTotal, max)), gdpTotal) + 
  geom_histogram(stat="identity") 

```




